//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewRating
    {
        public int ReviewID { get; set; }
        public Nullable<int> CarOwnerID { get; set; }
        public Nullable<int> RenterID { get; set; }
        public Nullable<int> CarListingID { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual CarListing CarListing { get; set; }
        public virtual CarOwner CarOwner { get; set; }
        public virtual Renter Renter { get; set; }
    }
}
