//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnapDriveDBEntities : DbContext
    {
        public SnapDriveDBEntities()
            : base("name=SnapDriveDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUserRole> AdminUserRoles { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<CarListing> CarListings { get; set; }
        public virtual DbSet<CarOwner> CarOwners { get; set; }
        public virtual DbSet<Communication> Communications { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<LocationGeoData> LocationGeoDatas { get; set; }
        public virtual DbSet<LogsAuditTrail> LogsAuditTrails { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Renter> Renters { get; set; }
        public virtual DbSet<ReviewRating> ReviewRatings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
